config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server, at: '/cable'
  match '/calculate_investment', to: 'investments#calculate_investment', via: [:get, :post]

  resources :investments do

      post 'export_csv', on: :collection, defaults: { format: :csv }
      post 'export_json', on: :collection, defaults: { format: :json }

  end

  root :to=> 'investments#calculate_investment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :investments

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  validates :balance, presence: true
  validates :bitcoin_investment, presence: true
  validates :ether_investment, presence: true
  validates :cardano_investment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController
end

app/controllers/investments_controller.rb
# app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_coinapi_service

  def calculate_investment
    if request.post?
      params[:balance] = 0 unless params[:balance].present?
      params[:bitcoin_investment] = 0 unless params[:bitcoin_investment].present?
      params[:ether_investment] = 0 unless params[:ether_investment].present?
      params[:cardano_investment] = 0 unless params[:cardano_investment].present?

      balance = params[:balance].to_i
      bitcoin_investment = params[:bitcoin_investment].to_i
      ether_investment = params[:ether_investment].to_i
      cardano_investment = params[:cardano_investment].to_i
      if balance > 0 && bitcoin_investment > 0 && ether_investment > 0 && cardano_investment > 0
        @cryptocurrency_data = obtener_datos_criptomonedas(balance, bitcoin_investment, ether_investment, cardano_investment)
        @balance = balance
        @bitcoin_investment = bitcoin_investment
        @ether_investment = ether_investment
        @cardano_investment = cardano_investment
        render partial: 'data_result'
        return
      end
    end
    render 'calculate_investment'
  end

  def export_csv
    respond_to do |format|
      format.csv do
        send_data generate_csv(params[:balance].to_i, params[:bitcoin_investment].to_i, params[:ether_investment].to_i, params[:cardano_investment].to_i), filename: "cryptocurrency_data_#{Time.now.strftime('%Y%m%d%H%M%S')}.csv"
      end
    end
  end

  def export_json
    data = obtener_datos_criptomonedas(params[:balance].to_i, params[:bitcoin_investment].to_i, params[:ether_investment].to_i, params[:cardano_investment].to_i)
    json_data = data.to_json

    respond_to do |format|
      format.json do
        send_data json_data, filename: "cryptocurrency_data_#{Time.now.strftime('%Y%m%d%H%M%S')}.json"
      end
    end
  end

  private

  def set_coinapi_service
    api_key = 'bd5570c4-4a1e-46d7-bd4a-176f0dae6a5b'
    @coinapi_service = CoinapiService.new(api_key)
  end

  def generate_csv(balance, bitcoin_investment, ether_investment, cardano_investment)
    data = obtener_datos_criptomonedas(balance, bitcoin_investment, ether_investment, cardano_investment)
    CSV.generate(headers: true) do |csv|
      csv << ['Criptomoneda', 'Precio (USD)', 'Ganancia en USD por año']
      data.each do |row|
        csv << [row['name'], row['price'], row['profit_per_year']]
      end
    end
  end

  def obtener_datos_criptomonedas(balance, bitcoin_investment, ether_investment, cardano_investment)
    bitcoin_data = @coinapi_service.cryptocurrency_data('BTC')
    ether_data = @coinapi_service.cryptocurrency_data('ETH')
    cardano_data = @coinapi_service.cryptocurrency_data('ADA')

    [
      { 'name' => 'Bitcoin', 'price' => bitcoin_data['rate'], 'profit_per_year' => profit_per_year(bitcoin_data['rate'].to_i, bitcoin_investment, 0.05) },
      { 'name' => 'Ether', 'price' => ether_data['rate'], 'profit_per_year' => profit_per_year(ether_data['rate'].to_i, ether_investment, 0.042) },
      { 'name' => 'Cardano', 'price' => cardano_data['rate'], 'profit_per_year' => profit_per_year(cardano_data['rate'].to_i, cardano_investment, 0.01) }
    ]
  end

  def profit_per_year(rate, investment, monthly_return)
    tasa_mensual = monthly_return / 100.0
    tasa_anual = (1 + tasa_mensual) ** 12 - 1

    ganancia_anual = rate * tasa_anual * investment
    ganancia_anual.round(8)
  end

  def user_params
    params.require(:user).permit(:balance, :bitcoin_investment, :ether_investment, :cardano_investment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptocurrencies_helper.rb
module CryptocurrenciesHelper
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_data_result.html.erb
<%= stylesheet_link_tag 'application' %>
<% if @cryptocurrency_data.present? %>
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title"><h1>Detalles de tu inversión</h1></div>
        <div class="ibox-content">
          <table class="table footable table-header" data-show-toggle="false" data-expand-fisrt="true">
            <thead>
            <tr>
              <th class="text-left">Criptomoneda</th>
              <th class="text-left">Precio (USD)</th>
              <th class="text-left">Ganancia en USD por año</th>
            </tr>
            </thead>
            <tbody>
            <% @cryptocurrency_data.each do |data| %>
              <tr>
                <td class="text-left"><%= data['name'] %></td>
                <td class="text-left"><%= data['price'] %> USD</td>
                <td class="text-left"><%= data['profit_per_year'] %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          <%= link_to 'Volver', root_path, class: 'btn btn-primary' %>
          <%= form_tag(export_csv_investments_path(format: :csv), method: :post) do %>
            <%= hidden_field_tag :balance, @balance %>
            <%= hidden_field_tag :bitcoin_investment, @bitcoin_investment %>
            <%= hidden_field_tag :ether_investment, @ether_investment %>
            <%= hidden_field_tag :cardano_investment, @cardano_investment %>
            <%= submit_tag 'Exportar a CSV', class: 'btn btn-primary' %>
          <% end %>

          <%= form_tag(export_json_investments_path(format: :json), method: :post) do %>
            <%= hidden_field_tag :balance, @balance %>
            <%= hidden_field_tag :bitcoin_investment, @bitcoin_investment %>
            <%= hidden_field_tag :ether_investment, @ether_investment %>
            <%= hidden_field_tag :cardano_investment, @cardano_investment %>
            <%= submit_tag 'Exportar a JSON', class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/investments/calculate_investment.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title"><h1>Calculadora de inversión</h1></div>
      <div class="ibox-content">
        <%= form_with(model: @user, url: calculate_investment_path, method: :post, remote: true) do |form| %>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-6 col-6">
              <div class="form-group mt-1">
                <%= form.label :balance, 'Balance en dólares' %>
                <%= form.number_field :balance, class: "form-control", placeholder: "Cantidad en dolares" %>
              </div>
            </div>


            <div class="col-lg-6 col-md-6 col-xs-6 col-6">
              <div class="form-group mt-1">
                <%= form.label :bitcoin_investment, 'Inversión en Bitcoin' %>
                <%= form.number_field :bitcoin_investment, class: "form-control", placeholder: "Cantidad en dolares" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-6 col-md-6 col-xs-6 col-6">
              <div class="form-group mt-1">
                <%= form.label :ether_investment, 'Inversión en Ether' %>
                <%= form.number_field :ether_investment, class: "form-control", placeholder: "Cantidad en dolares" %>
              </div>
            </div>

            <div class="col-lg-6 col-md-6 col-xs-6 col-6">
              <div class="form-group mt-1">
                <%= form.label :cardano_investment, 'Inversión en Cardano' %>
                <%= form.number_field :cardano_investment, class: "form-control", placeholder: "Cantidad en dolares" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12 col-12">
              <div class="form-group">
                <%= form.submit 'Calcular Inversión', class: "btn btn-primary w-100 mb-3 mt-2" %>
              </div>
            </div>
          </div>

        <% end %>
        <div class="row">
          <div class="col-lg-12 col-md-12 col-xs-12 col-12">
            <div class="table footable" id="data_result">

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Criptomonedas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>